apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 2
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: oleg0puntia/my-app
        ports:
        - containerPort: 80
        env:
          - name: ConnectionStrings__ProductsContext
            valueFrom:
              secretKeyRef:
                name: db-connection-secret
                key: db-connection-string-secret
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: LoadBalancer
  selector:
    app: myapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
